### ISSUE TITLE
carrousel - no funciona boton flecha

### ISSUE THREAD

**Issue by KatuGT** [DanaYael/ProyectoFinal#7]
![image](https://github.com/user-attachments/assets/a6efd9c2-9b85-4192-8c6f-c4913035566f)

al hacer click no pasa al siguiete item

**Comment by IgnacioRMN** [comment]
Se reestructuró el código de tal manera que cumple con las correcciones dadas, con el carrusel funcionando además de la implementación de un botón adicional para pasar. En esta modificación también esta incluida la corrección al issue anterior que superponía los iconos a la información que se introducía al formulario.

**Comment by KatuGT** [comment]
listo, ahora funciona!
